"use client";

import { useState } from "react";
import type { DocEntry, ProjectConfig, AgentConfig } from "@/lib/mission-control-data";

function AuthorBadge({ author, agents }: { author: string; agents: AgentConfig[] }) {
  const agent = agents.find((a) => a.id === author);
  const isHuman = author === "human";
  const color = agent?.provider === "claude" ? "#a78bfa" : agent?.provider === "codex" ? "#4ade80" : "#7dd3fc";
  return (
    <div className="flex items-center gap-1.5">
      <span className="w-5 h-5 rounded-full flex items-center justify-center text-[9px] font-bold"
        style={{ background: `${color}20`, color }}>
        {(agent?.name || author).charAt(0).toUpperCase()}
      </span>
      <span className="text-[11px]" style={{ color: "var(--text-muted)" }}>
        {agent?.name || (isHuman ? "You" : author)}
      </span>
    </div>
  );
}

export function DocsScreen({
  agentDocs,
  agents,
  projects,
}: {
  agentDocs: DocEntry[];
  agents: AgentConfig[];
  projects: ProjectConfig[];
}) {
  const [search, setSearch] = useState("");
  const [selectedProject, setSelectedProject] = useState("all");
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = agentDocs.filter((d) => {
    const matchSearch = !search || d.title.toLowerCase().includes(search.toLowerCase()) || d.content.toLowerCase().includes(search.toLowerCase());
    const matchProject = selectedProject === "all" || d.project === selectedProject;
    return matchSearch && matchProject;
  });

  // Group by date
  const byDate = new Map<string, DocEntry[]>();
  for (const doc of filtered) {
    const date = doc.createdAt.split("T")[0];
    if (!byDate.has(date)) byDate.set(date, []);
    byDate.get(date)!.push(doc);
  }
  const sortedDates = [...byDate.keys()].sort().reverse();

  const getProject = (id?: string) => projects.find((p) => p.id === id);

  return (
    <div className="p-6 overflow-y-auto h-full animate-fade-in">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold mb-1" style={{ color: "var(--text-primary)" }}>Documents</h2>
          <p className="text-[13px]" style={{ color: "var(--text-muted)" }}>
            {agentDocs.length} docs generated by agents, organized by date
          </p>
        </div>
        <input
          type="text" value={search} onChange={(e) => setSearch(e.target.value)}
          placeholder="Search docs..."
          className="w-64 px-3 py-2 rounded-lg text-[13px] outline-none border-0"
          style={{ background: "var(--bg-secondary)", color: "var(--text-primary)", border: "1px solid var(--border-primary)" }}
        />
      </div>

      {/* Project filter */}
      <div className="flex items-center gap-2 mb-6">
        <span className="text-[11px] font-medium" style={{ color: "var(--text-muted)" }}>Project</span>
        <select
          value={selectedProject}
          onChange={(e) => setSelectedProject(e.target.value)}
          className="px-3 py-1.5 rounded-lg text-[12px] cursor-pointer border-0 outline-none"
          style={{ background: "var(--bg-secondary)", color: "var(--text-primary)", border: "1px solid var(--border-subtle)" }}
        >
          <option value="all">All projects</option>
          {projects.map((p) => (
            <option key={p.id} value={p.id}>{p.name}</option>
          ))}
        </select>
      </div>

      {/* Docs by date */}
      {sortedDates.map((date) => {
        const docs = byDate.get(date)!;
        const dateObj = new Date(date + "T00:00:00");
        const isToday = new Date().toISOString().split("T")[0] === date;

        return (
          <div key={date} className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <span className="text-[13px] font-semibold" style={{ color: isToday ? "var(--accent-violet)" : "var(--text-primary)" }}>
                {isToday ? "Today" : dateObj.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric" })}
              </span>
              <span className="text-[11px]" style={{ color: "var(--text-muted)" }}>{docs.length} docs</span>
            </div>
            <div className="flex flex-col gap-2">
              {docs.map((doc) => {
                const proj = getProject(doc.project);
                const isExp = expanded === doc.id;
                return (
                  <div key={doc.id}
                    onClick={() => setExpanded(isExp ? null : doc.id)}
                    className="rounded-xl p-4 cursor-pointer transition-colors duration-150"
                    style={{ background: isExp ? "var(--bg-card-hover)" : "var(--bg-card)", border: `1px solid ${isExp ? "var(--border-primary)" : "var(--border-subtle)"}` }}
                    onMouseEnter={(e) => { if (!isExp) e.currentTarget.style.background = "var(--bg-card-hover)"; }}
                    onMouseLeave={(e) => { if (!isExp) e.currentTarget.style.background = "var(--bg-card)"; }}
                  >
                    <div className="flex items-start justify-between mb-2">
                      <div className="flex items-center gap-2">
                        {proj && <span className="w-2 h-2 rounded-full" style={{ background: proj.color }} />}
                        <h3 className="text-[13px] font-medium" style={{ color: "var(--text-primary)" }}>{doc.title}</h3>
                      </div>
                      <span className="text-[10px] flex-shrink-0 ml-4" style={{ color: "var(--text-muted)" }}>
                        {new Date(doc.createdAt).toLocaleTimeString()}
                      </span>
                    </div>
                    <div className="flex items-center gap-3">
                      <AuthorBadge author={doc.author} agents={agents} />
                      {proj && <span className="text-[11px]" style={{ color: "var(--text-muted)" }}>{proj.name}</span>}
                    </div>
                    {isExp && (
                      <div className="mt-3 pt-3 animate-fade-in" style={{ borderTop: "1px solid var(--border-primary)" }}>
                        <pre className="text-[12px] leading-relaxed whitespace-pre-wrap font-sans" style={{ color: "var(--text-secondary)" }}>
                          {doc.content}
                        </pre>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        );
      })}

      {agentDocs.length === 0 && (
        <div className="py-12 text-center text-[13px]" style={{ color: "var(--text-muted)" }}>
          No documents yet — agents will create docs as they complete tasks
        </div>
      )}
    </div>
  );
}
